// ============ LEVEL SYSTEM ============

export type LevelConfig = {
  id: number;
  name: string;
  emoji: string;
  description: string;
  survivalTime: number;        // milliseconds (60000 = 1 min)
  gridSize: number;            // 10, 12, 15, or 20
  initialSnakeLength: number;  // starting segments
  initialSnakeSpeed: number;   // ms per move (lower = faster)
  speedIncreaseInterval: number;   // ms between speed increases (0 = no increase)
  speedIncreaseAmount: number;     // ms to reduce per interval
  growInterval: number;        // ms between growth (0 = no growth)
  growAmount: number;          // segments added per growth
  hasProjectiles: boolean;
  projectileInterval: number;  // ms between shots (if enabled)
  projectileCount: number;     // projectiles per shot
  hasPowerFood: boolean;
  powerFoodInterval: number;   // ms between spawns
  powerFoodSpeedBoost: number; // ms snake gains when eating food
  powerFoodSizeBoost: number;  // segments snake gains when eating food
  specialModifier?: 'invisible' | 'shrinking_arena' | 'chaos' | 'titan' | 'perfect_ai' | 'momentum';
};

// Base difficulty: Similar to previous "hard" mode
// Speed: 5ms faster every 2 seconds (reaches ~90ms at 60s)
// Growth: 1 block every 2 seconds (reaches ~33 segments at 60s)

export const LEVELS: LevelConfig[] = [
  {
    id: 1,
    name: 'Classic',
    emoji: '🎮',
    description: 'Standard gameplay - learn the basics',
    survivalTime: 60000,
    gridSize: 20,
    initialSnakeLength: 4,
    initialSnakeSpeed: 120,       // Faster start
    speedIncreaseInterval: 2000,  // Speed up every 2s
    speedIncreaseAmount: 5,       // 5ms faster each time
    growInterval: 2000,           // Grow every 2s
    growAmount: 1,
    hasProjectiles: false,
    projectileInterval: 0,
    projectileCount: 0,
    hasPowerFood: true,
    powerFoodInterval: 8000,
    powerFoodSpeedBoost: 3,
    powerFoodSizeBoost: 2,
  },
  {
    id: 2,
    name: 'Speed Demon',
    emoji: '⚡',
    description: 'Snake starts very fast',
    survivalTime: 60000,
    gridSize: 20,
    initialSnakeLength: 4,
    initialSnakeSpeed: 90,        // Very fast start
    speedIncreaseInterval: 2500,
    speedIncreaseAmount: 4,
    growInterval: 2500,
    growAmount: 1,
    hasProjectiles: false,
    projectileInterval: 0,
    projectileCount: 0,
    hasPowerFood: true,
    powerFoodInterval: 7000,
    powerFoodSpeedBoost: 3,
    powerFoodSizeBoost: 2,
  },
  {
    id: 3,
    name: 'Tiny Arena',
    emoji: '📦',
    description: '15x15 grid - less room to escape',
    survivalTime: 60000,
    gridSize: 15,
    initialSnakeLength: 4,
    initialSnakeSpeed: 130,
    speedIncreaseInterval: 2000,
    speedIncreaseAmount: 4,
    growInterval: 2500,
    growAmount: 1,
    hasProjectiles: false,
    projectileInterval: 0,
    projectileCount: 0,
    hasPowerFood: true,
    powerFoodInterval: 7000,
    powerFoodSpeedBoost: 3,
    powerFoodSizeBoost: 2,
  },
  {
    id: 4,
    name: 'Accelerator',
    emoji: '🐢',
    description: 'Starts slow, accelerates rapidly',
    survivalTime: 60000,
    gridSize: 20,
    initialSnakeLength: 4,
    initialSnakeSpeed: 160,
    speedIncreaseInterval: 1500,  // Very frequent speed ups
    speedIncreaseAmount: 6,       // Big jumps
    growInterval: 2000,
    growAmount: 1,
    hasProjectiles: false,
    projectileInterval: 0,
    projectileCount: 0,
    hasPowerFood: true,
    powerFoodInterval: 8000,
    powerFoodSpeedBoost: 3,
    powerFoodSizeBoost: 2,
  },
  {
    id: 5,
    name: 'Sniper',
    emoji: '🎯',
    description: 'Snake shoots projectiles every 4 seconds',
    survivalTime: 60000,
    gridSize: 20,
    initialSnakeLength: 4,
    initialSnakeSpeed: 120,
    speedIncreaseInterval: 2500,
    speedIncreaseAmount: 4,
    growInterval: 2500,
    growAmount: 1,
    hasProjectiles: true,
    projectileInterval: 4000,
    projectileCount: 1,
    hasPowerFood: true,
    powerFoodInterval: 8000,
    powerFoodSpeedBoost: 3,
    powerFoodSizeBoost: 2,
  },
  {
    id: 6,
    name: 'Power Surge',
    emoji: '⭐',
    description: 'Power food spawns frequently but boosts snake more',
    survivalTime: 60000,
    gridSize: 20,
    initialSnakeLength: 4,
    initialSnakeSpeed: 120,
    speedIncreaseInterval: 2000,
    speedIncreaseAmount: 4,
    growInterval: 2500,
    growAmount: 1,
    hasProjectiles: false,
    projectileInterval: 0,
    projectileCount: 0,
    hasPowerFood: true,
    powerFoodInterval: 4000,      // Frequent spawns
    powerFoodSpeedBoost: 5,       // Big boost
    powerFoodSizeBoost: 3,
  },
  {
    id: 7,
    name: 'Marathon',
    emoji: '🏃',
    description: '3 minutes - constant acceleration',
    survivalTime: 180000,
    gridSize: 20,
    initialSnakeLength: 4,
    initialSnakeSpeed: 150,
    speedIncreaseInterval: 1500,
    speedIncreaseAmount: 2,
    growInterval: 4000,
    growAmount: 1,
    hasProjectiles: false,
    projectileInterval: 0,
    projectileCount: 0,
    hasPowerFood: true,
    powerFoodInterval: 8000,
    powerFoodSpeedBoost: 3,
    powerFoodSizeBoost: 2,
    specialModifier: 'momentum',
  },
  {
    id: 8,
    name: 'Claustrophobia',
    emoji: '😰',
    description: '12x12 grid - tight spaces',
    survivalTime: 60000,
    gridSize: 12,
    initialSnakeLength: 4,
    initialSnakeSpeed: 130,
    speedIncreaseInterval: 2500,
    speedIncreaseAmount: 4,
    growInterval: 3000,
    growAmount: 1,
    hasProjectiles: false,
    projectileInterval: 0,
    projectileCount: 0,
    hasPowerFood: true,
    powerFoodInterval: 8000,
    powerFoodSpeedBoost: 3,
    powerFoodSizeBoost: 2,
  },
  {
    id: 9,
    name: 'Glutton',
    emoji: '🍔',
    description: 'Snake grows 2 blocks at a time',
    survivalTime: 60000,
    gridSize: 20,
    initialSnakeLength: 4,
    initialSnakeSpeed: 120,
    speedIncreaseInterval: 2000,
    speedIncreaseAmount: 4,
    growInterval: 2000,
    growAmount: 2,                // Double growth
    hasProjectiles: false,
    projectileInterval: 0,
    projectileCount: 0,
    hasPowerFood: true,
    powerFoodInterval: 8000,
    powerFoodSpeedBoost: 3,
    powerFoodSizeBoost: 2,
  },
  {
    id: 10,
    name: 'Hyperspeed',
    emoji: '🚀',
    description: 'Everything at 1.5x speed',
    survivalTime: 60000,
    gridSize: 20,
    initialSnakeLength: 4,
    initialSnakeSpeed: 90,
    speedIncreaseInterval: 1500,
    speedIncreaseAmount: 5,
    growInterval: 1500,
    growAmount: 1,
    hasProjectiles: false,
    projectileInterval: 0,
    projectileCount: 0,
    hasPowerFood: true,
    powerFoodInterval: 5000,
    powerFoodSpeedBoost: 4,
    powerFoodSizeBoost: 2,
  },
  {
    id: 11,
    name: 'Long Boi',
    emoji: '🐍',
    description: 'Snake starts with 10 segments',
    survivalTime: 60000,
    gridSize: 20,
    initialSnakeLength: 10,       // Long start
    initialSnakeSpeed: 120,
    speedIncreaseInterval: 2000,
    speedIncreaseAmount: 4,
    growInterval: 2500,
    growAmount: 1,
    hasProjectiles: false,
    projectileInterval: 0,
    projectileCount: 0,
    hasPowerFood: true,
    powerFoodInterval: 8000,
    powerFoodSpeedBoost: 3,
    powerFoodSizeBoost: 2,
  },
  {
    id: 12,
    name: 'Famine',
    emoji: '🏜️',
    description: 'No power food spawns - pure survival',
    survivalTime: 60000,
    gridSize: 20,
    initialSnakeLength: 4,
    initialSnakeSpeed: 120,
    speedIncreaseInterval: 2000,
    speedIncreaseAmount: 5,
    growInterval: 2000,
    growAmount: 1,
    hasProjectiles: false,
    projectileInterval: 0,
    projectileCount: 0,
    hasPowerFood: false,
    powerFoodInterval: 0,
    powerFoodSpeedBoost: 0,
    powerFoodSizeBoost: 0,
  },
  {
    id: 13,
    name: 'Feast',
    emoji: '🍕',
    description: 'Power food gives massive boost to snake',
    survivalTime: 60000,
    gridSize: 20,
    initialSnakeLength: 4,
    initialSnakeSpeed: 130,
    speedIncreaseInterval: 2500,
    speedIncreaseAmount: 3,
    growInterval: 3000,
    growAmount: 1,
    hasProjectiles: false,
    projectileInterval: 0,
    projectileCount: 0,
    hasPowerFood: true,
    powerFoodInterval: 6000,
    powerFoodSpeedBoost: 8,       // Huge boost
    powerFoodSizeBoost: 4,
  },
  {
    id: 14,
    name: 'Marksman',
    emoji: '🏹',
    description: 'Projectiles every 3 seconds',
    survivalTime: 60000,
    gridSize: 20,
    initialSnakeLength: 4,
    initialSnakeSpeed: 120,
    speedIncreaseInterval: 2000,
    speedIncreaseAmount: 4,
    growInterval: 2500,
    growAmount: 1,
    hasProjectiles: true,
    projectileInterval: 3000,
    projectileCount: 1,
    hasPowerFood: true,
    powerFoodInterval: 8000,
    powerFoodSpeedBoost: 3,
    powerFoodSizeBoost: 2,
  },
  {
    id: 15,
    name: 'Micro',
    emoji: '🔬',
    description: '10x10 arena - smallest battlefield',
    survivalTime: 60000,
    gridSize: 10,
    initialSnakeLength: 3,
    initialSnakeSpeed: 140,
    speedIncreaseInterval: 3000,
    speedIncreaseAmount: 4,
    growInterval: 3000,
    growAmount: 1,
    hasProjectiles: false,
    projectileInterval: 0,
    projectileCount: 0,
    hasPowerFood: true,
    powerFoodInterval: 8000,
    powerFoodSpeedBoost: 3,
    powerFoodSizeBoost: 2,
  },
  {
    id: 16,
    name: 'Patience',
    emoji: '🧘',
    description: 'No speed increase, but grows every 1.5s',
    survivalTime: 60000,
    gridSize: 20,
    initialSnakeLength: 4,
    initialSnakeSpeed: 110,
    speedIncreaseInterval: 0,
    speedIncreaseAmount: 0,
    growInterval: 1500,           // Rapid growth
    growAmount: 1,
    hasProjectiles: false,
    projectileInterval: 0,
    projectileCount: 0,
    hasPowerFood: true,
    powerFoodInterval: 8000,
    powerFoodSpeedBoost: 3,
    powerFoodSizeBoost: 2,
  },
  {
    id: 17,
    name: 'Ambush',
    emoji: '👻',
    description: 'Snake invisible 0.5s every 3s',
    survivalTime: 60000,
    gridSize: 20,
    initialSnakeLength: 4,
    initialSnakeSpeed: 120,
    speedIncreaseInterval: 2000,
    speedIncreaseAmount: 4,
    growInterval: 2500,
    growAmount: 1,
    hasProjectiles: false,
    projectileInterval: 0,
    projectileCount: 0,
    hasPowerFood: true,
    powerFoodInterval: 8000,
    powerFoodSpeedBoost: 3,
    powerFoodSizeBoost: 2,
    specialModifier: 'invisible',
  },
  {
    id: 18,
    name: 'Titan',
    emoji: '🦖',
    description: 'Giant slow snake - 2x segment size',
    survivalTime: 60000,
    gridSize: 20,
    initialSnakeLength: 6,
    initialSnakeSpeed: 180,
    speedIncreaseInterval: 3000,
    speedIncreaseAmount: 6,
    growInterval: 3000,
    growAmount: 1,
    hasProjectiles: false,
    projectileInterval: 0,
    projectileCount: 0,
    hasPowerFood: true,
    powerFoodInterval: 8000,
    powerFoodSpeedBoost: 3,
    powerFoodSizeBoost: 2,
    specialModifier: 'titan',
  },
  {
    id: 19,
    name: 'Barrage',
    emoji: '💥',
    description: '3 projectiles at once in spread pattern',
    survivalTime: 60000,
    gridSize: 20,
    initialSnakeLength: 4,
    initialSnakeSpeed: 120,
    speedIncreaseInterval: 2500,
    speedIncreaseAmount: 4,
    growInterval: 2500,
    growAmount: 1,
    hasProjectiles: true,
    projectileInterval: 4000,
    projectileCount: 3,
    hasPowerFood: true,
    powerFoodInterval: 8000,
    powerFoodSpeedBoost: 3,
    powerFoodSizeBoost: 2,
  },
  {
    id: 20,
    name: 'Momentum',
    emoji: '📈',
    description: 'Constant acceleration - gets crazy fast',
    survivalTime: 60000,
    gridSize: 20,
    initialSnakeLength: 4,
    initialSnakeSpeed: 150,
    speedIncreaseInterval: 400,   // Very frequent
    speedIncreaseAmount: 2,       // Gets to ~50ms at 60s
    growInterval: 2500,
    growAmount: 1,
    hasProjectiles: false,
    projectileInterval: 0,
    projectileCount: 0,
    hasPowerFood: true,
    powerFoodInterval: 8000,
    powerFoodSpeedBoost: 3,
    powerFoodSizeBoost: 2,
    specialModifier: 'momentum',
  },
  {
    id: 21,
    name: 'Risk/Reward',
    emoji: '🎁',
    description: 'Power food helps player more but spawns rarely',
    survivalTime: 60000,
    gridSize: 20,
    initialSnakeLength: 4,
    initialSnakeSpeed: 110,
    speedIncreaseInterval: 2000,
    speedIncreaseAmount: 5,
    growInterval: 2000,
    growAmount: 1,
    hasProjectiles: false,
    projectileInterval: 0,
    projectileCount: 0,
    hasPowerFood: true,
    powerFoodInterval: 12000,     // Rare spawns
    powerFoodSpeedBoost: 2,
    powerFoodSizeBoost: 1,
  },
  {
    id: 22,
    name: 'Predator',
    emoji: '🦈',
    description: 'Perfect AI - no randomness in movement',
    survivalTime: 60000,
    gridSize: 20,
    initialSnakeLength: 4,
    initialSnakeSpeed: 110,
    speedIncreaseInterval: 2000,
    speedIncreaseAmount: 4,
    growInterval: 2500,
    growAmount: 1,
    hasProjectiles: false,
    projectileInterval: 0,
    projectileCount: 0,
    hasPowerFood: true,
    powerFoodInterval: 8000,
    powerFoodSpeedBoost: 3,
    powerFoodSizeBoost: 2,
    specialModifier: 'perfect_ai',
  },
  {
    id: 23,
    name: 'Chaos',
    emoji: '🎲',
    description: 'Random speed changes every 4s',
    survivalTime: 60000,
    gridSize: 20,
    initialSnakeLength: 4,
    initialSnakeSpeed: 120,
    speedIncreaseInterval: 0,
    speedIncreaseAmount: 0,
    growInterval: 2000,
    growAmount: 1,
    hasProjectiles: false,
    projectileInterval: 0,
    projectileCount: 0,
    hasPowerFood: true,
    powerFoodInterval: 8000,
    powerFoodSpeedBoost: 3,
    powerFoodSizeBoost: 2,
    specialModifier: 'chaos',
  },
  {
    id: 24,
    name: 'Zen',
    emoji: '☯️',
    description: 'Slow snake, but arena shrinks over time',
    survivalTime: 60000,
    gridSize: 20,
    initialSnakeLength: 4,
    initialSnakeSpeed: 160,
    speedIncreaseInterval: 3000,
    speedIncreaseAmount: 3,
    growInterval: 3000,
    growAmount: 1,
    hasProjectiles: false,
    projectileInterval: 0,
    projectileCount: 0,
    hasPowerFood: true,
    powerFoodInterval: 8000,
    powerFoodSpeedBoost: 3,
    powerFoodSizeBoost: 2,
    specialModifier: 'shrinking_arena',
  },
  {
    id: 25,
    name: 'Nightmare',
    emoji: '😱',
    description: 'Fast snake + small arena + starts long',
    survivalTime: 60000,
    gridSize: 12,
    initialSnakeLength: 6,
    initialSnakeSpeed: 100,
    speedIncreaseInterval: 2000,
    speedIncreaseAmount: 5,
    growInterval: 2000,
    growAmount: 1,
    hasProjectiles: false,
    projectileInterval: 0,
    projectileCount: 0,
    hasPowerFood: true,
    powerFoodInterval: 8000,
    powerFoodSpeedBoost: 3,
    powerFoodSizeBoost: 2,
  },
  {
    id: 26,
    name: 'Machine Gun',
    emoji: '🔫',
    description: 'Projectiles every 2 seconds',
    survivalTime: 60000,
    gridSize: 20,
    initialSnakeLength: 4,
    initialSnakeSpeed: 120,
    speedIncreaseInterval: 2500,
    speedIncreaseAmount: 4,
    growInterval: 2500,
    growAmount: 1,
    hasProjectiles: true,
    projectileInterval: 2000,
    projectileCount: 1,
    hasPowerFood: true,
    powerFoodInterval: 8000,
    powerFoodSpeedBoost: 3,
    powerFoodSizeBoost: 2,
  },
  {
    id: 27,
    name: 'Endurance',
    emoji: '💪',
    description: '3 minutes - fast snake, minimal growth',
    survivalTime: 180000,
    gridSize: 20,
    initialSnakeLength: 4,
    initialSnakeSpeed: 100,
    speedIncreaseInterval: 3000,
    speedIncreaseAmount: 2,
    growInterval: 6000,
    growAmount: 1,
    hasProjectiles: false,
    projectileInterval: 0,
    projectileCount: 0,
    hasPowerFood: true,
    powerFoodInterval: 8000,
    powerFoodSpeedBoost: 2,
    powerFoodSizeBoost: 1,
  },
  {
    id: 28,
    name: 'Rapid Growth',
    emoji: '🌱',
    description: 'Snake grows every 1 second',
    survivalTime: 60000,
    gridSize: 20,
    initialSnakeLength: 4,
    initialSnakeSpeed: 120,
    speedIncreaseInterval: 2500,
    speedIncreaseAmount: 4,
    growInterval: 1000,           // Extremely fast growth
    growAmount: 1,
    hasProjectiles: false,
    projectileInterval: 0,
    projectileCount: 0,
    hasPowerFood: true,
    powerFoodInterval: 8000,
    powerFoodSpeedBoost: 3,
    powerFoodSizeBoost: 2,
  },
  {
    id: 29,
    name: 'Final Form',
    emoji: '⚔️',
    description: 'Max speed from start, no growth',
    survivalTime: 60000,
    gridSize: 20,
    initialSnakeLength: 4,
    initialSnakeSpeed: 55,        // Very fast
    speedIncreaseInterval: 0,
    speedIncreaseAmount: 0,
    growInterval: 0,
    growAmount: 0,
    hasProjectiles: false,
    projectileInterval: 0,
    projectileCount: 0,
    hasPowerFood: true,
    powerFoodInterval: 8000,
    powerFoodSpeedBoost: 0,
    powerFoodSizeBoost: 0,
  },
  {
    id: 30,
    name: 'Ultimate',
    emoji: '👑',
    description: '3 min - Fast, small arena, rapid projectiles',
    survivalTime: 180000,
    gridSize: 12,
    initialSnakeLength: 6,
    initialSnakeSpeed: 90,
    speedIncreaseInterval: 2000,
    speedIncreaseAmount: 3,
    growInterval: 2000,
    growAmount: 1,
    hasProjectiles: true,
    projectileInterval: 2500,
    projectileCount: 2,
    hasPowerFood: true,
    powerFoodInterval: 6000,
    powerFoodSpeedBoost: 3,
    powerFoodSizeBoost: 2,
  },
];

export const getLevel = (id: number): LevelConfig | undefined => {
  return LEVELS.find(l => l.id === id);
};

export const TOTAL_LEVELS = LEVELS.length;
