// ============ LEVEL SYSTEM ============

export type LevelConfig = {
  id: number;
  name: string;
  emoji: string;
  description: string;
  survivalTime: number;        // milliseconds
  gridSize: number;            // grid dimension
  initialSnakeLength: number;  // starting segments
  maxSnakeLength: number;      // hard cap on snake length
  initialSnakeSpeed: number;   // ms per move (lower = faster)
  speedIncreaseInterval: number;   // ms between speed increases
  speedIncreaseAmount: number;     // ms to reduce per interval
  growInterval: number;        // ms between growth (0 = food-based only)
  growAmount: number;          // segments added per growth tick
  hasProjectiles: boolean;
  projectileInterval: number;  // ms between shots (if enabled)
  projectileCount: number;     // projectiles per shot
  hasPowerFood: boolean;
  powerFoodInterval: number;   // ms between spawns
  powerFoodSpeedBoost: number; // speed boost when snake eats food
  powerFoodSizeBoost: number;  // segments snake gains when eating food
  specialModifier?: 'invisible' | 'shrinking_arena' | 'chaos' | 'titan' | 'perfect_ai' | 'momentum';
  shrinkToSize?: number;       // for shrinking arena levels
};

// Speed rules:
// - Max speed cap: 30ms (cannot go faster)
// - Grid > 15: +5 speed every 2 seconds (very aggressive)
// - Grid <= 15: +3 speed every 3 seconds (aggressive but less room)
// Max snake length by grid size:
// 22×22: 20 | 20×20: 18 | 18×18: 14 | 15×15: 10 | 14×14: 9 | 12×12: 8 | 10×10: 6

export const LEVELS: LevelConfig[] = [
  {
    id: 1,
    name: 'Classic',
    emoji: '🎮',
    description: 'Standard gameplay - learn the basics',
    survivalTime: 45000,
    gridSize: 22,
    initialSnakeLength: 3,
    maxSnakeLength: 20,
    initialSnakeSpeed: 160,
    speedIncreaseInterval: 2000,  // grid > 15: every 2s
    speedIncreaseAmount: 5,       // +5ms faster
    growInterval: 0,
    growAmount: 0,
    hasProjectiles: false,
    projectileInterval: 0,
    projectileCount: 0,
    hasPowerFood: true,
    powerFoodInterval: 3500,
    powerFoodSpeedBoost: 0,
    powerFoodSizeBoost: 1,
  },
  {
    id: 2,
    name: 'Speed Demon',
    emoji: '⚡',
    description: 'Snake starts faster',
    survivalTime: 45000,
    gridSize: 22,
    initialSnakeLength: 3,
    maxSnakeLength: 20,
    initialSnakeSpeed: 130,       // faster start
    speedIncreaseInterval: 2000,
    speedIncreaseAmount: 5,
    growInterval: 0,
    growAmount: 0,
    hasProjectiles: false,
    projectileInterval: 0,
    projectileCount: 0,
    hasPowerFood: true,
    powerFoodInterval: 3500,
    powerFoodSpeedBoost: 0,
    powerFoodSizeBoost: 1,
  },
  {
    id: 3,
    name: 'Tiny Arena',
    emoji: '📦',
    description: '18x18 grid - less room to escape',
    survivalTime: 50000,
    gridSize: 18,
    initialSnakeLength: 3,
    maxSnakeLength: 14,
    initialSnakeSpeed: 160,
    speedIncreaseInterval: 2000,  // grid > 15: every 2s
    speedIncreaseAmount: 5,
    growInterval: 0,
    growAmount: 0,
    hasProjectiles: false,
    projectileInterval: 0,
    projectileCount: 0,
    hasPowerFood: true,
    powerFoodInterval: 4000,
    powerFoodSpeedBoost: 0,
    powerFoodSizeBoost: 1,
  },
  {
    id: 4,
    name: 'Accelerator',
    emoji: '🐢',
    description: 'Starts slow but speeds up fast',
    survivalTime: 50000,
    gridSize: 22,
    initialSnakeLength: 3,
    maxSnakeLength: 20,
    initialSnakeSpeed: 180,       // slower start
    speedIncreaseInterval: 2000,
    speedIncreaseAmount: 5,
    growInterval: 0,
    growAmount: 0,
    hasProjectiles: false,
    projectileInterval: 0,
    projectileCount: 0,
    hasPowerFood: true,
    powerFoodInterval: 4000,
    powerFoodSpeedBoost: 0,
    powerFoodSizeBoost: 1,
  },
  {
    id: 5,
    name: 'Sniper',
    emoji: '🎯',
    description: 'Snake shoots projectiles every 5 seconds',
    survivalTime: 55000,
    gridSize: 22,
    initialSnakeLength: 4,
    maxSnakeLength: 20,
    initialSnakeSpeed: 150,
    speedIncreaseInterval: 2000,
    speedIncreaseAmount: 5,
    growInterval: 0,
    growAmount: 0,
    hasProjectiles: true,
    projectileInterval: 5000,
    projectileCount: 1,
    hasPowerFood: true,
    powerFoodInterval: 4000,
    powerFoodSpeedBoost: 0,
    powerFoodSizeBoost: 1,
  },
  {
    id: 6,
    name: 'Power Surge',
    emoji: '⭐',
    description: 'Power food boosts snake speed and size',
    survivalTime: 55000,
    gridSize: 22,
    initialSnakeLength: 4,
    maxSnakeLength: 20,
    initialSnakeSpeed: 160,
    speedIncreaseInterval: 2000,
    speedIncreaseAmount: 5,
    growInterval: 0,
    growAmount: 0,
    hasProjectiles: false,
    projectileInterval: 0,
    projectileCount: 0,
    hasPowerFood: true,
    powerFoodInterval: 3000,
    powerFoodSpeedBoost: 5,       // +speed per power food
    powerFoodSizeBoost: 2,
  },
  {
    id: 7,
    name: 'Marathon',
    emoji: '🏃',
    description: '2 minutes of endurance',
    survivalTime: 120000,
    gridSize: 22,
    initialSnakeLength: 4,
    maxSnakeLength: 20,
    initialSnakeSpeed: 170,
    speedIncreaseInterval: 2000,
    speedIncreaseAmount: 5,
    growInterval: 0,
    growAmount: 0,
    hasProjectiles: false,
    projectileInterval: 0,
    projectileCount: 0,
    hasPowerFood: true,
    powerFoodInterval: 4500,
    powerFoodSpeedBoost: 0,
    powerFoodSizeBoost: 1,
    specialModifier: 'momentum',
  },
  {
    id: 8,
    name: 'Claustrophobia',
    emoji: '😰',
    description: '14x14 grid - tight spaces',
    survivalTime: 55000,
    gridSize: 14,
    initialSnakeLength: 4,
    maxSnakeLength: 9,
    initialSnakeSpeed: 170,
    speedIncreaseInterval: 3000,  // grid <= 15: every 3s
    speedIncreaseAmount: 3,
    growInterval: 0,
    growAmount: 0,
    hasProjectiles: false,
    projectileInterval: 0,
    projectileCount: 0,
    hasPowerFood: true,
    powerFoodInterval: 4500,
    powerFoodSpeedBoost: 0,
    powerFoodSizeBoost: 1,
  },
  {
    id: 9,
    name: 'Glutton',
    emoji: '🍔',
    description: 'Snake grows 2 segments per food',
    survivalTime: 55000,
    gridSize: 20,
    initialSnakeLength: 4,
    maxSnakeLength: 18,
    initialSnakeSpeed: 155,
    speedIncreaseInterval: 2000,
    speedIncreaseAmount: 5,
    growInterval: 0,
    growAmount: 0,
    hasProjectiles: false,
    projectileInterval: 0,
    projectileCount: 0,
    hasPowerFood: true,
    powerFoodInterval: 4000,
    powerFoodSpeedBoost: 0,
    powerFoodSizeBoost: 2,
  },
  {
    id: 10,
    name: 'Hyperspeed',
    emoji: '🚀',
    description: 'Time-based growth + fast start',
    survivalTime: 50000,
    gridSize: 20,
    initialSnakeLength: 5,
    maxSnakeLength: 18,
    initialSnakeSpeed: 120,       // fast start
    speedIncreaseInterval: 2000,
    speedIncreaseAmount: 5,
    growInterval: 1500,
    growAmount: 1,
    hasProjectiles: false,
    projectileInterval: 0,
    projectileCount: 0,
    hasPowerFood: true,
    powerFoodInterval: 4000,
    powerFoodSpeedBoost: 0,
    powerFoodSizeBoost: 1,
  },
  {
    id: 11,
    name: 'Long Boi',
    emoji: '🐍',
    description: 'Snake starts with 8 segments',
    survivalTime: 55000,
    gridSize: 20,
    initialSnakeLength: 8,
    maxSnakeLength: 18,
    initialSnakeSpeed: 155,
    speedIncreaseInterval: 2000,
    speedIncreaseAmount: 5,
    growInterval: 0,
    growAmount: 0,
    hasProjectiles: false,
    projectileInterval: 0,
    projectileCount: 0,
    hasPowerFood: true,
    powerFoodInterval: 4000,
    powerFoodSpeedBoost: 0,
    powerFoodSizeBoost: 1,
  },
  {
    id: 12,
    name: 'Famine',
    emoji: '🏜️',
    description: 'Rare food spawns',
    survivalTime: 60000,
    gridSize: 20,
    initialSnakeLength: 5,
    maxSnakeLength: 18,
    initialSnakeSpeed: 160,
    speedIncreaseInterval: 2000,
    speedIncreaseAmount: 5,
    growInterval: 0,
    growAmount: 0,
    hasProjectiles: false,
    projectileInterval: 0,
    projectileCount: 0,
    hasPowerFood: true,
    powerFoodInterval: 6000,
    powerFoodSpeedBoost: 0,
    powerFoodSizeBoost: 1,
  },
  {
    id: 13,
    name: 'Feast',
    emoji: '🍕',
    description: 'Frequent food with massive boosts',
    survivalTime: 55000,
    gridSize: 20,
    initialSnakeLength: 5,
    maxSnakeLength: 18,
    initialSnakeSpeed: 165,
    speedIncreaseInterval: 2000,
    speedIncreaseAmount: 5,
    growInterval: 0,
    growAmount: 0,
    hasProjectiles: false,
    projectileInterval: 0,
    projectileCount: 0,
    hasPowerFood: true,
    powerFoodInterval: 3000,
    powerFoodSpeedBoost: 8,
    powerFoodSizeBoost: 3,
  },
  {
    id: 14,
    name: 'Marksman',
    emoji: '🏹',
    description: 'Projectiles every 4 seconds',
    survivalTime: 60000,
    gridSize: 20,
    initialSnakeLength: 6,
    maxSnakeLength: 18,
    initialSnakeSpeed: 155,
    speedIncreaseInterval: 2000,
    speedIncreaseAmount: 5,
    growInterval: 0,
    growAmount: 0,
    hasProjectiles: true,
    projectileInterval: 4000,
    projectileCount: 1,
    hasPowerFood: true,
    powerFoodInterval: 4000,
    powerFoodSpeedBoost: 0,
    powerFoodSizeBoost: 1,
  },
  {
    id: 15,
    name: 'Micro',
    emoji: '🔬',
    description: '12x12 arena - smallest battlefield',
    survivalTime: 45000,
    gridSize: 12,
    initialSnakeLength: 4,
    maxSnakeLength: 8,
    initialSnakeSpeed: 175,
    speedIncreaseInterval: 3000,  // grid <= 15: every 3s
    speedIncreaseAmount: 3,
    growInterval: 0,
    growAmount: 0,
    hasProjectiles: false,
    projectileInterval: 0,
    projectileCount: 0,
    hasPowerFood: true,
    powerFoodInterval: 4500,
    powerFoodSpeedBoost: 0,
    powerFoodSizeBoost: 1,
  },
  {
    id: 16,
    name: 'Patience',
    emoji: '🧘',
    description: 'Constant time-based growth every 1.5s',
    survivalTime: 60000,
    gridSize: 20,
    initialSnakeLength: 6,
    maxSnakeLength: 18,
    initialSnakeSpeed: 155,
    speedIncreaseInterval: 2000,
    speedIncreaseAmount: 5,
    growInterval: 1500,
    growAmount: 1,
    hasProjectiles: false,
    projectileInterval: 0,
    projectileCount: 0,
    hasPowerFood: true,
    powerFoodInterval: 4000,
    powerFoodSpeedBoost: 0,
    powerFoodSizeBoost: 1,
  },
  {
    id: 17,
    name: 'Ambush',
    emoji: '👻',
    description: 'Snake turns invisible periodically',
    survivalTime: 60000,
    gridSize: 20,
    initialSnakeLength: 6,
    maxSnakeLength: 18,
    initialSnakeSpeed: 155,
    speedIncreaseInterval: 2000,
    speedIncreaseAmount: 5,
    growInterval: 0,
    growAmount: 0,
    hasProjectiles: false,
    projectileInterval: 0,
    projectileCount: 0,
    hasPowerFood: true,
    powerFoodInterval: 4500,
    powerFoodSpeedBoost: 0,
    powerFoodSizeBoost: 1,
    specialModifier: 'invisible',
  },
  {
    id: 18,
    name: 'Titan',
    emoji: '🦖',
    description: 'Giant slow snake - 2x segment size',
    survivalTime: 60000,
    gridSize: 20,
    initialSnakeLength: 6,
    maxSnakeLength: 18,
    initialSnakeSpeed: 200,
    speedIncreaseInterval: 2000,
    speedIncreaseAmount: 5,
    growInterval: 0,
    growAmount: 0,
    hasProjectiles: false,
    projectileInterval: 0,
    projectileCount: 0,
    hasPowerFood: true,
    powerFoodInterval: 5000,
    powerFoodSpeedBoost: 0,
    powerFoodSizeBoost: 1,
    specialModifier: 'titan',
  },
  {
    id: 19,
    name: 'Barrage',
    emoji: '💥',
    description: '3 projectiles in spread pattern',
    survivalTime: 65000,
    gridSize: 20,
    initialSnakeLength: 7,
    maxSnakeLength: 18,
    initialSnakeSpeed: 155,
    speedIncreaseInterval: 2000,
    speedIncreaseAmount: 5,
    growInterval: 0,
    growAmount: 0,
    hasProjectiles: true,
    projectileInterval: 4500,
    projectileCount: 3,
    hasPowerFood: true,
    powerFoodInterval: 4000,
    powerFoodSpeedBoost: 0,
    powerFoodSizeBoost: 1,
  },
  {
    id: 20,
    name: 'Momentum',
    emoji: '📈',
    description: 'Aggressive momentum modifier',
    survivalTime: 60000,
    gridSize: 20,
    initialSnakeLength: 7,
    maxSnakeLength: 18,
    initialSnakeSpeed: 180,
    speedIncreaseInterval: 2000,
    speedIncreaseAmount: 5,
    growInterval: 0,
    growAmount: 0,
    hasProjectiles: false,
    projectileInterval: 0,
    projectileCount: 0,
    hasPowerFood: true,
    powerFoodInterval: 4500,
    powerFoodSpeedBoost: 0,
    powerFoodSizeBoost: 1,
    specialModifier: 'momentum',
  },
  {
    id: 21,
    name: 'Risk/Reward',
    emoji: '🎁',
    description: 'Power food spawns rarely - fight for it',
    survivalTime: 70000,
    gridSize: 20,
    initialSnakeLength: 6,
    maxSnakeLength: 18,
    initialSnakeSpeed: 160,
    speedIncreaseInterval: 2000,
    speedIncreaseAmount: 5,
    growInterval: 0,
    growAmount: 0,
    hasProjectiles: false,
    projectileInterval: 0,
    projectileCount: 0,
    hasPowerFood: true,
    powerFoodInterval: 5500,
    powerFoodSpeedBoost: 4,
    powerFoodSizeBoost: 1,
  },
  {
    id: 22,
    name: 'Predator',
    emoji: '🦈',
    description: 'Perfect AI - snake always takes optimal path',
    survivalTime: 60000,
    gridSize: 20,
    initialSnakeLength: 7,
    maxSnakeLength: 18,
    initialSnakeSpeed: 155,
    speedIncreaseInterval: 2000,
    speedIncreaseAmount: 5,
    growInterval: 0,
    growAmount: 0,
    hasProjectiles: false,
    projectileInterval: 0,
    projectileCount: 0,
    hasPowerFood: true,
    powerFoodInterval: 5000,
    powerFoodSpeedBoost: 0,
    powerFoodSizeBoost: 1,
    specialModifier: 'perfect_ai',
  },
  {
    id: 23,
    name: 'Chaos',
    emoji: '🎲',
    description: 'Random speed changes + base acceleration',
    survivalTime: 65000,
    gridSize: 20,
    initialSnakeLength: 7,
    maxSnakeLength: 18,
    initialSnakeSpeed: 160,
    speedIncreaseInterval: 2000,
    speedIncreaseAmount: 5,
    growInterval: 0,
    growAmount: 0,
    hasProjectiles: false,
    projectileInterval: 0,
    projectileCount: 0,
    hasPowerFood: true,
    powerFoodInterval: 4000,
    powerFoodSpeedBoost: 0,
    powerFoodSizeBoost: 1,
    specialModifier: 'chaos',
  },
  {
    id: 24,
    name: 'Zen',
    emoji: '☯️',
    description: 'Slow snake, but arena shrinks from 22 to 14',
    survivalTime: 75000,
    gridSize: 22,
    initialSnakeLength: 6,
    maxSnakeLength: 20,
    initialSnakeSpeed: 180,
    speedIncreaseInterval: 2000,
    speedIncreaseAmount: 5,
    growInterval: 0,
    growAmount: 0,
    hasProjectiles: false,
    projectileInterval: 0,
    projectileCount: 0,
    hasPowerFood: true,
    powerFoodInterval: 5000,
    powerFoodSpeedBoost: 0,
    powerFoodSizeBoost: 1,
    specialModifier: 'shrinking_arena',
    shrinkToSize: 14,
  },
  {
    id: 25,
    name: 'Nightmare',
    emoji: '😱',
    description: 'Fast snake + tiny 12x12 arena',
    survivalTime: 45000,
    gridSize: 12,
    initialSnakeLength: 6,
    maxSnakeLength: 8,
    initialSnakeSpeed: 130,       // fast in small arena
    speedIncreaseInterval: 3000,  // grid <= 15: every 3s
    speedIncreaseAmount: 3,
    growInterval: 0,
    growAmount: 0,
    hasProjectiles: false,
    projectileInterval: 0,
    projectileCount: 0,
    hasPowerFood: true,
    powerFoodInterval: 4500,
    powerFoodSpeedBoost: 0,
    powerFoodSizeBoost: 1,
  },
  {
    id: 26,
    name: 'Machine Gun',
    emoji: '🔫',
    description: 'Projectiles every 3 seconds',
    survivalTime: 60000,
    gridSize: 20,
    initialSnakeLength: 7,
    maxSnakeLength: 18,
    initialSnakeSpeed: 155,
    speedIncreaseInterval: 2000,
    speedIncreaseAmount: 5,
    growInterval: 0,
    growAmount: 0,
    hasProjectiles: true,
    projectileInterval: 3000,
    projectileCount: 1,
    hasPowerFood: true,
    powerFoodInterval: 4000,
    powerFoodSpeedBoost: 0,
    powerFoodSizeBoost: 1,
  },
  {
    id: 27,
    name: 'Endurance',
    emoji: '💪',
    description: '2:30 marathon - rare food',
    survivalTime: 150000,
    gridSize: 20,
    initialSnakeLength: 7,
    maxSnakeLength: 18,
    initialSnakeSpeed: 165,
    speedIncreaseInterval: 2000,
    speedIncreaseAmount: 5,
    growInterval: 0,
    growAmount: 0,
    hasProjectiles: false,
    projectileInterval: 0,
    projectileCount: 0,
    hasPowerFood: true,
    powerFoodInterval: 6000,
    powerFoodSpeedBoost: 0,
    powerFoodSizeBoost: 1,
  },
  {
    id: 28,
    name: 'Rapid Growth',
    emoji: '🌱',
    description: 'Snake grows every 1 second',
    survivalTime: 55000,
    gridSize: 20,
    initialSnakeLength: 6,
    maxSnakeLength: 18,
    initialSnakeSpeed: 155,
    speedIncreaseInterval: 2000,
    speedIncreaseAmount: 5,
    growInterval: 1000,
    growAmount: 1,
    hasProjectiles: false,
    projectileInterval: 0,
    projectileCount: 0,
    hasPowerFood: true,
    powerFoodInterval: 4000,
    powerFoodSpeedBoost: 0,
    powerFoodSizeBoost: 1,
  },
  {
    id: 29,
    name: 'Final Form',
    emoji: '⚔️',
    description: 'Fast start, no growth, no food - pure dodging',
    survivalTime: 45000,
    gridSize: 20,
    initialSnakeLength: 8,
    maxSnakeLength: 8,
    initialSnakeSpeed: 90,        // very fast start
    speedIncreaseInterval: 2000,
    speedIncreaseAmount: 5,
    growInterval: 0,
    growAmount: 0,
    hasProjectiles: false,
    projectileInterval: 0,
    projectileCount: 0,
    hasPowerFood: false,
    powerFoodInterval: 0,
    powerFoodSpeedBoost: 0,
    powerFoodSizeBoost: 0,
  },
  {
    id: 30,
    name: 'Ultimate',
    emoji: '👑',
    description: '2 min - tiny arena, growth, projectiles',
    survivalTime: 120000,
    gridSize: 14,
    initialSnakeLength: 8,
    maxSnakeLength: 9,
    initialSnakeSpeed: 145,
    speedIncreaseInterval: 3000,  // grid <= 15: every 3s
    speedIncreaseAmount: 3,
    growInterval: 1500,
    growAmount: 1,
    hasProjectiles: true,
    projectileInterval: 4000,
    projectileCount: 2,
    hasPowerFood: true,
    powerFoodInterval: 4000,
    powerFoodSpeedBoost: 4,
    powerFoodSizeBoost: 1,
  },
];

export const getLevel = (id: number): LevelConfig | undefined => {
  return LEVELS.find(l => l.id === id);
};

export const TOTAL_LEVELS = LEVELS.length;

// Grid size to max snake length mapping
export const getMaxSnakeLengthForGrid = (gridSize: number): number => {
  if (gridSize >= 22) return 20;
  if (gridSize >= 20) return 18;
  if (gridSize >= 18) return 14;
  if (gridSize >= 15) return 10;
  if (gridSize >= 14) return 9;
  if (gridSize >= 12) return 8;
  return 6;
};

// Speed increase rules by grid size
export const getSpeedIncreaseForGrid = (gridSize: number): { interval: number; amount: number } => {
  if (gridSize > 15) {
    return { interval: 2000, amount: 5 }; // +5 every 2s for larger grids (very aggressive)
  }
  return { interval: 3000, amount: 3 };   // +3 every 3s for smaller grids
};
